# Generated by Django 6.1 on 2026-08-12 07:40

import lockers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='token',
            field=models.CharField(default=lockers.models.generate_locker_token, editable=False, max_length=100, unique=True),
        ),
    ]
