# Generated by Django 6.0.1 on 2026-08-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_auto_token_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for access notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS/WhatsApp alerts', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Annual rent fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='locker',
            name='lease_end_date',
            field=models.DateField(blank=True, help_text='Expiration date of lease agreement', null=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='lease_start_date',
            field=models.DateField(blank=True, help_text='Start date of lease agreement', null=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending Payment'), ('overdue', 'Payment Overdue')], default='paid', max_length=20),
        ),
    ]
