# Generated by Django 6.0.1 on 2026-08-25 11:19

import lockers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0003_customer_email_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_proof_file',
            field=models.FileField(help_text='Accepted formats: PDF, JPG, PNG. Max 5 MB.', upload_to='id_proofs/', validators=[lockers.models.validate_id_proof_file]),
        ),
    ]
