# Generated by Django 6.0.1 on 2026-08-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0004_alter_customer_id_proof_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Locker Created'), ('edited', 'Locker Updated'), ('assigned', 'Customer Assigned'), ('unassigned', 'Customer Removed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_activities', to='lockers.customer')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lockers.locker')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
