# Generated by Django 6.0.1 on 2026-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0005_lockeractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockeractivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Locker Created'), ('edited', 'Locker Updated'), ('assigned', 'Customer Assigned'), ('unassigned', 'Customer Removed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('deleted', 'Locker Deleted')], max_length=50),
        ),
    ]
