# Generated by Django 6.0.1 on 2026-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0006_alter_lockeractivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Unique Customer ID', max_length=50, null=True),
        ),
    ]
