# Generated by Django 6.0.1 on 2026-09-05 08:40

import lockers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0007_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=lockers.models.generate_customer_id, help_text='Unique Customer ID', max_length=50, unique=True),
        ),
    ]
